---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-${KUBE_NAMESPACE}
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi