# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint & Test Python package

on:
  push:
    paths-ignore:
      - '**.md'
  release:
    types:
      - released  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3.3.0

    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11
        architecture: x64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: Lint with flake8
      run: |
        # exit-zero treats all errors as warnings. 
        flake8 app/ --count --exit-zero --max-complexity=10 --max-line-length=120 --show-source --statistics
        flake8 test/ --count --exit-zero --max-complexity=10 --max-line-length=120 --show-source --statistics

    - name: Test with pytest
      run: |
        python -m pytest         

 