# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint & Test Python package

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  lint_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        architecture: x64

    - name: Ensure Nexus mirror configuration is not committed
      run: |
        # Grep checks for Nexus mirror in the index-url parameter,
        # the ! negates the grep exit code, which would be 0 if URL was present
        ! grep -E '.*index-url.*nexus.*' requirements*.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dependencies for testing
      run: |
        pip install -r requirements_dev.txt

    - name: Lint app/ and test/ with flake8
      run: |
        flake8 app/ test/
        
    - name: Test with pytest
      run: |
        python -m pytest         

    




    
 
